// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data_access;

namespace api_bakum.Migrations
{
    [DbContext(typeof(DBBakumContext))]
    [Migration("20180531152714_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("data_access.entities.BantuanHukum", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agama");

                    b.Property<string>("Email");

                    b.Property<string>("FileName");

                    b.Property<string>("Identitas");

                    b.Property<string>("IsiPermohonan");

                    b.Property<string>("JenisKelamin");

                    b.Property<int?>("KewarganegaraanCountryID");

                    b.Property<string>("NamaLengkap");

                    b.Property<string>("NoIdentitas");

                    b.Property<string>("Pekerjaan");

                    b.Property<string>("Telpn");

                    b.Property<int>("Umur");

                    b.HasKey("ID");

                    b.HasIndex("KewarganegaraanCountryID");

                    b.ToTable("BantuanHukum");
                });

            modelBuilder.Entity("data_access.entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("data_access.entities.BantuanHukum", b =>
                {
                    b.HasOne("data_access.entities.Country", "Kewarganegaraan")
                        .WithMany()
                        .HasForeignKey("KewarganegaraanCountryID");
                });
#pragma warning restore 612, 618
        }
    }
}
